/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *button4;
  GtkWidget *treeview1;
  GtkWidget *button3;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);
  gtk_widget_set_size_request (fixed1, 900, 900);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 152, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 152, 96);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 104);
  gtk_widget_set_size_request (label2, 96, 16);

  label1 = gtk_label_new (_("username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 56);
  gtk_widget_set_size_request (label1, 104, 16);

  button1 = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 152, 136);
  gtk_widget_set_size_request (button1, 68, 29);

  button4 = gtk_button_new_from_stock ("ajouter");
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 200, 192);
  gtk_widget_set_size_request (button4, 68, 29);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 352, 64);
  gtk_widget_set_size_request (treeview1, 300, 200);

  button3 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 232, 136);
  gtk_widget_set_size_request (button3, 68, 29);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, label2, "label2");
  GLADE_HOOKUP_OBJECT (login, label1, "label1");
  GLADE_HOOKUP_OBJECT (login, button1, "button1");
  GLADE_HOOKUP_OBJECT (login, button4, "button4");
  GLADE_HOOKUP_OBJECT (login, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (login, button3, "button3");

  return login;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed2;
  GtkWidget *label3;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (admin), _("admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (admin), fixed2);

  label3 = gtk_label_new (_("bienvenu dans l'espace admin"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 64, 128);
  gtk_widget_set_size_request (label3, 264, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (admin, label3, "label3");

  return admin;
}

GtkWidget*
create_medecin (void)
{
  GtkWidget *medecin;
  GtkWidget *fixed4;
  GtkWidget *label6;
  GtkWidget *button5;
  GtkWidget *button6;

  medecin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (medecin, 633, 668);
  gtk_window_set_title (GTK_WINDOW (medecin), _("medecin"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (medecin), fixed4);

  label6 = gtk_label_new (_("bienvenu dans l'espace m\303\251decin"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 184, 264);
  gtk_widget_set_size_request (label6, 248, 17);

  button5 = gtk_button_new_with_mnemonic (_("FICHE MEDICALE"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 216, 96);
  gtk_widget_set_size_request (button5, 180, 32);

  button6 = gtk_button_new_with_mnemonic (_("FICHE NUTRITONNELLE"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 216, 168);
  gtk_widget_set_size_request (button6, 180, 32);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (medecin, medecin, "medecin");
  GLADE_HOOKUP_OBJECT (medecin, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (medecin, label6, "label6");
  GLADE_HOOKUP_OBJECT (medecin, button5, "button5");
  GLADE_HOOKUP_OBJECT (medecin, button6, "button6");

  return medecin;
}

GtkWidget*
create_clients (void)
{
  GtkWidget *clients;
  GtkWidget *fixed3;
  GtkWidget *label4;
  GtkWidget *label5;

  clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (clients), _("clients"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (clients), fixed3);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 144, 144);
  gtk_widget_set_size_request (label4, 41, 17);

  label5 = gtk_label_new (_("bienvenu dans l'espace clients"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 64, 112);
  gtk_widget_set_size_request (label5, 280, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (clients, clients, "clients");
  GLADE_HOOKUP_OBJECT (clients, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (clients, label4, "label4");
  GLADE_HOOKUP_OBJECT (clients, label5, "label5");

  return clients;
}

GtkWidget*
create_coach (void)
{
  GtkWidget *coach;
  GtkWidget *fixed5;
  GtkWidget *label7;

  coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (coach), _("coach"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (coach), fixed5);

  label7 = gtk_label_new (_("bienvenu dans l'espace coach"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 152, 128);
  gtk_widget_set_size_request (label7, 41, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (coach, coach, "coach");
  GLADE_HOOKUP_OBJECT (coach, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (coach, label7, "label7");

  return coach;
}

GtkWidget*
create_error (void)
{
  GtkWidget *error;
  GtkWidget *fixed6;
  GtkWidget *label8;

  error = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (error), _("error"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (error), fixed6);

  label8 = gtk_label_new (_("error"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed6), label8, 144, 129);
  gtk_widget_set_size_request (label8, 96, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error, error, "error");
  GLADE_HOOKUP_OBJECT (error, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (error, label8, "label8");

  return error;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed7;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *Button2;
  GtkWidget *label11;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajouter user"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ajout), fixed7);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3, 144, 24);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4, 144, 72);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 144, 120);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label9 = gtk_label_new (_("username"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed7), label9, 24, 32);
  gtk_widget_set_size_request (label9, 104, 17);

  label10 = gtk_label_new (_("password"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed7), label10, 40, 80);
  gtk_widget_set_size_request (label10, 73, 17);

  Button2 = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (Button2);
  gtk_fixed_put (GTK_FIXED (fixed7), Button2, 160, 176);
  gtk_widget_set_size_request (Button2, 68, 29);

  label11 = gtk_label_new (_("fonction"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed7), label11, 24, 120);
  gtk_widget_set_size_request (label11, 88, 25);

  g_signal_connect ((gpointer) Button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ajout, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajout, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajout, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajout, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajout, Button2, "Button2");
  GLADE_HOOKUP_OBJECT (ajout, label11, "label11");

  return ajout;
}

GtkWidget*
create_ajouterFM (void)
{
  GtkWidget *ajouterFM;
  GtkWidget *fixed8;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *label24;
  GtkWidget *button14;
  GtkWidget *combobox2;
  GtkWidget *combobox3;
  GtkWidget *combobox4;
  GtkWidget *combobox1;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label25;

  ajouterFM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajouterFM, 651, 485);
  gtk_window_set_title (GTK_WINDOW (ajouterFM), _("ajouterFM"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (ajouterFM), fixed8);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed8), entry6, 120, 40);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed8), entry7, 120, 72);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbutton1_adj = gtk_adjustment_new (6, 6, 70, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton1, 120, 144);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (150, 50, 150, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton4, 120, 176);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (120, 120, 300, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton5, 120, 208);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  label24 = gtk_label_new (_(" Ajouter Fiche  Medicale"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed8), label24, 240, 8);
  gtk_widget_set_size_request (label24, 200, 31);

  button14 = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed8), button14, 272, 344);
  gtk_widget_set_size_request (button14, 80, 29);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox2, 120, 240);
  gtk_widget_set_size_request (combobox2, 80, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Oui"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("X"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox3, 120, 272);
  gtk_widget_set_size_request (combobox3, 80, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Oui"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("X"));

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox4, 120, 304);
  gtk_widget_set_size_request (combobox4, 80, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("*D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("x"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("*PY"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("*L"));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox1, 120, 104);
  gtk_widget_set_size_request (combobox1, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("femme "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("homme"));

  label13 = gtk_label_new (_("Nom"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed8), label13, 24, 40);
  gtk_widget_set_size_request (label13, 80, 30);

  label14 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed8), label14, 32, 72);
  gtk_widget_set_size_request (label14, 80, 30);

  label15 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed8), label15, 24, 104);
  gtk_widget_set_size_request (label15, 80, 30);

  label16 = gtk_label_new (_("Age"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed8), label16, 32, 144);
  gtk_widget_set_size_request (label16, 80, 30);

  label20 = gtk_label_new (_("Poids"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed8), label20, 32, 176);
  gtk_widget_set_size_request (label20, 80, 30);

  label21 = gtk_label_new (_("Taille"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed8), label21, 24, 208);
  gtk_widget_set_size_request (label21, 80, 30);

  label22 = gtk_label_new (_("MaladieC"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed8), label22, 40, 240);
  gtk_widget_set_size_request (label22, 80, 30);

  label23 = gtk_label_new (_("Allergie"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed8), label23, 40, 264);
  gtk_widget_set_size_request (label23, 80, 30);

  label25 = gtk_label_new (_("Notices"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed8), label25, 40, 296);
  gtk_widget_set_size_request (label25, 80, 30);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouterFM, ajouterFM, "ajouterFM");
  GLADE_HOOKUP_OBJECT (ajouterFM, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (ajouterFM, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (ajouterFM, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajouterFM, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouterFM, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (ajouterFM, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (ajouterFM, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajouterFM, button14, "button14");
  GLADE_HOOKUP_OBJECT (ajouterFM, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (ajouterFM, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (ajouterFM, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (ajouterFM, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajouterFM, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouterFM, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouterFM, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouterFM, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajouterFM, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajouterFM, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajouterFM, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajouterFM, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajouterFM, label25, "label25");

  return ajouterFM;
}

GtkWidget*
create_ficheM (void)
{
  GtkWidget *ficheM;
  GtkWidget *fixed9;
  GtkWidget *treeview2;
  GtkWidget *button10;
  GtkWidget *button8;
  GtkWidget *button16;
  GtkWidget *button9;

  ficheM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ficheM, 500, 500);
  gtk_window_set_title (GTK_WINDOW (ficheM), _("ficheM"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (ficheM), fixed9);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview2, 72, 16);
  gtk_widget_set_size_request (treeview2, 408, 224);

  button10 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed9), button10, 392, 248);
  gtk_widget_set_size_request (button10, 80, 29);

  button8 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed9), button8, 216, 248);
  gtk_widget_set_size_request (button8, 80, 29);

  button16 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed9), button16, 128, 248);
  gtk_widget_set_size_request (button16, 80, 29);

  button9 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 304, 248);
  gtk_widget_set_size_request (button9, 80, 29);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ficheM, ficheM, "ficheM");
  GLADE_HOOKUP_OBJECT (ficheM, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (ficheM, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (ficheM, button10, "button10");
  GLADE_HOOKUP_OBJECT (ficheM, button8, "button8");
  GLADE_HOOKUP_OBJECT (ficheM, button16, "button16");
  GLADE_HOOKUP_OBJECT (ficheM, button9, "button9");

  return ficheM;
}

GtkWidget*
create_ficheN (void)
{
  GtkWidget *ficheN;
  GtkWidget *fixed10;
  GtkWidget *treeview3;
  GtkWidget *button13;
  GtkWidget *button12;
  GtkWidget *button11;
  GtkWidget *button17;

  ficheN = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ficheN, 500, 500);
  gtk_window_set_title (GTK_WINDOW (ficheN), _("ficheN"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (ficheN), fixed10);
  gtk_widget_set_size_request (fixed10, 500, 500);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 64, 8);
  gtk_widget_set_size_request (treeview3, 424, 248);

  button13 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed10), button13, 400, 272);
  gtk_widget_set_size_request (button13, 90, 29);

  button12 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed10), button12, 304, 272);
  gtk_widget_set_size_request (button12, 90, 29);

  button11 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed10), button11, 208, 272);
  gtk_widget_set_size_request (button11, 90, 29);

  button17 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed10), button17, 120, 272);
  gtk_widget_set_size_request (button17, 80, 29);

  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ficheN, ficheN, "ficheN");
  GLADE_HOOKUP_OBJECT (ficheN, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (ficheN, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (ficheN, button13, "button13");
  GLADE_HOOKUP_OBJECT (ficheN, button12, "button12");
  GLADE_HOOKUP_OBJECT (ficheN, button11, "button11");
  GLADE_HOOKUP_OBJECT (ficheN, button17, "button17");

  return ficheN;
}

GtkWidget*
create_ajouterFN (void)
{
  GtkWidget *ajouterFN;
  GtkWidget *fixed11;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *label35;
  GtkWidget *button15;
  GtkWidget *combobox5;
  GtkWidget *combobox6;
  GtkWidget *label34;
  GtkWidget *label33;
  GtkWidget *label32;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *label28;

  ajouterFN = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajouterFN, 500, 500);
  gtk_window_set_title (GTK_WINDOW (ajouterFN), _("ajouterFN"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (ajouterFN), fixed11);
  gtk_widget_set_size_request (fixed11, 350, 350);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed11), entry8, 136, 48);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed11), entry9, 136, 80);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  spinbutton6_adj = gtk_adjustment_new (6, 6, 75, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton6, 136, 152);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (50, 50, 150, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton7, 136, 184);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (120, 120, 300, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton8, 136, 216);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  label35 = gtk_label_new (_("ajouter fiche nutritionnelle"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed11), label35, 152, 8);
  gtk_widget_set_size_request (label35, 200, 31);

  button15 = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed11), button15, 208, 408);
  gtk_widget_set_size_request (button15, 76, 29);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox5, 136, 112);
  gtk_widget_set_size_request (combobox5, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("homme "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("femme"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox6, 136, 248);
  gtk_widget_set_size_request (combobox6, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("X"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Hypocalorique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Sans Sel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Sans r\303\251sidu"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Sans gluten"));

  label34 = gtk_label_new (_("Regime"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed11), label34, 48, 248);
  gtk_widget_set_size_request (label34, 80, 30);

  label33 = gtk_label_new (_("Taille"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed11), label33, 40, 216);
  gtk_widget_set_size_request (label33, 80, 30);

  label32 = gtk_label_new (_("Poids"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed11), label32, 40, 184);
  gtk_widget_set_size_request (label32, 80, 30);

  label31 = gtk_label_new (_("Age"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed11), label31, 40, 152);
  gtk_widget_set_size_request (label31, 80, 30);

  label30 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed11), label30, 40, 112);
  gtk_widget_set_size_request (label30, 80, 30);

  label29 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed11), label29, 48, 80);
  gtk_widget_set_size_request (label29, 80, 30);

  label28 = gtk_label_new (_("Nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed11), label28, 40, 48);
  gtk_widget_set_size_request (label28, 80, 30);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouterFN, ajouterFN, "ajouterFN");
  GLADE_HOOKUP_OBJECT (ajouterFN, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (ajouterFN, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (ajouterFN, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (ajouterFN, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (ajouterFN, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (ajouterFN, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (ajouterFN, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajouterFN, button15, "button15");
  GLADE_HOOKUP_OBJECT (ajouterFN, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (ajouterFN, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (ajouterFN, label34, "label34");
  GLADE_HOOKUP_OBJECT (ajouterFN, label33, "label33");
  GLADE_HOOKUP_OBJECT (ajouterFN, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajouterFN, label31, "label31");
  GLADE_HOOKUP_OBJECT (ajouterFN, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajouterFN, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajouterFN, label28, "label28");

  return ajouterFN;
}

