/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_admin (void);
GtkWidget* create_medecin (void);
GtkWidget* create_clients (void);
GtkWidget* create_coach (void);
GtkWidget* create_error (void);
GtkWidget* create_ajout (void);
GtkWidget* create_ajouterFM (void);
GtkWidget* create_ficheM (void);
GtkWidget* create_ficheN (void);
GtkWidget* create_ajouterFN (void);
